//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public int ID { get; set; }
        public int JskID { get; set; }
        public int EmpID { get; set; }
        public string Titile { get; set; }
        public string Content { get; set; }
    
        public virtual Employer Employer { get; set; }
        public virtual Fb_Detail Fb_Detail { get; set; }
        public virtual User User { get; set; }
    }
}
